#!/bin/bash

# TODO: Get this working

css_file=~/.cache/wal/stylus-theme.user.css

color0=$(grep 'background:' ~/.cache/wal/colors.css | awk '{print $2}')
color1=$(grep 'foreground:' ~/.cache/wal/colors.css | awk '{print $2}')
color2=$(grep 'color1:' ~/.cache/wal/colors.css | awk '{print $2}')
color3=$(grep 'color2:' ~/.cache/wal/colors.css | awk '{print $2}')
color4=$(grep 'color3:' ~/.cache/wal/colors.css | awk '{print $2}')
color5=$(grep 'color4:' ~/.cache/wal/colors.css | awk '{print $2}')
color6=$(grep 'color5:' ~/.cache/wal/colors.css | awk '{print $2}')
color7=$(grep 'color6:' ~/.cache/wal/colors.css | awk '{print $2}')
color8=$(grep 'color7:' ~/.cache/wal/colors.css | awk '{print $2}')
color9=$(grep 'color8:' ~/.cache/wal/colors.css | awk '{print $2}')
color10=$(grep 'color9:' ~/.cache/wal/colors.css | awk '{print $2}')
color11=$(grep 'color10:' ~/.cache/wal/colors.css | awk '{print $2}')
color12=$(grep 'color11:' ~/.cache/wal/colors.css | awk '{print $2}')
color13=$(grep 'color12:' ~/.cache/wal/colors.css | awk '{print $2}')
color14=$(grep 'color13:' ~/.cache/wal/colors.css | awk '{print $2}')
color15=$(grep 'color14:' ~/.cache/wal/colors.css | awk '{print $2}')

cat > $css_file <<EOL
/* ==UserStyle==
@name           Pywal Theme
@namespace      pywal-stylus
@version        1.0
@description    A dynamic theme generated by pywal
@preprocessor   stylus
==/UserStyle== */

:root {
    --background-color: ${color0}
    --foreground-color: ${color1}
    --color1: ${color1}
    --color2: ${color2}
    --color3: ${color3}
    --color4: ${color4}
    --color5: ${color5}
    --color6: ${color6}
    --color7: ${color7}
    --color8: ${color8}
    --color9: ${color9}
    --color10: ${color10}
    --color11: ${color11}
    --color12: ${color12}
    --color13: ${color13}
    --color14: ${color14}
}

body {
    background-color: var(--background-color) !important;
    color: var(--foreground-color) !important;
}

* {
    color: var(--foreground-color) !important;
}

#slim-appbar {
    background-color: var(--background-color) !important;
}
EOL

PORT=7999

if lsof -i:$PORT -t > /dev/null; then
    PID=$(lsof -i:$PORT -t)
    kill $PID
    sleep 1
fi

cd ~/.cache/wal
python3 -m http.server $PORT
