#!/bin/bash

colors_json=~/.cache/wal/colors.json

wallpaper="$(jq -r '.wallpaper' $colors_json)"
color0="$(~/scripts/hex2rgb.sh $(jq -r '.colors.color0'  $colors_json))"
color1="$(~/scripts/hex2rgb.sh $(jq -r '.colors.color1'  $colors_json))"
color2="$(~/scripts/hex2rgb.sh $(jq -r '.colors.color2'  $colors_json))"
color3="$(~/scripts/hex2rgb.sh $(jq -r '.colors.color3'  $colors_json))"
color4="$(~/scripts/hex2rgb.sh $(jq -r '.colors.color4'  $colors_json))"
color5="$(~/scripts/hex2rgb.sh $(jq -r '.colors.color5'  $colors_json))"
color6="$(~/scripts/hex2rgb.sh $(jq -r '.colors.color6'  $colors_json))"
color7="$(~/scripts/hex2rgb.sh $(jq -r '.colors.color7'  $colors_json))"
color8="$(~/scripts/hex2rgb.sh $(jq -r '.colors.color8'  $colors_json))"
color9="$(~/scripts/hex2rgb.sh $(jq -r '.colors.color9'  $colors_json))"
color10="$(~/scripts/hex2rgb.sh $(jq -r '.colors.color10' $colors_json))"
color11="$(~/scripts/hex2rgb.sh $(jq -r '.colors.color11' $colors_json))"
color12="$(~/scripts/hex2rgb.sh $(jq -r '.colors.color12' $colors_json))"
color13="$(~/scripts/hex2rgb.sh $(jq -r '.colors.color13' $colors_json))"
color14="$(~/scripts/hex2rgb.sh $(jq -r '.colors.color14' $colors_json))"
color15="$(~/scripts/hex2rgb.sh $(jq -r '.colors.color15' $colors_json))"

hyprlock_conf=~/.config/hypr/hyprlock.conf
monitor=`hyprctl monitors | grep Monitor | awk '{print $2}' | sort | head -1`

cat <<eof > $hyprlock_conf

# This file is automatically generated. Do not edit.

background {
    monitor =
    path = $wallpaper
    color = rgba(25, 20, 20, 1.0)

    blur_passes = 3
    blur_size = 2
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor = $monitor
    size = 300, 30
    outline_thickness = 0
    dots_size = 0.25
    dots_spacing = 0.55
    dots_center = true
    dots_rounding = -1
    outer_color = rgba(242, 243, 244, 0)
    inner_color = rgba(242, 243, 244, 0)
    font_color = rgba(242, 243, 244, 0.75)
    fade_on_empty = false
    placeholder_text =
    hide_input = false
    check_color = rgba(204, 136, 34, 0)
    fail_color = rgba(204, 34, 34, 0)
    fail_text = $FAIL <b>($ATTEMPTS)</b>
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
    position = 0, -468
    halign = center
    valign = center
}

label {
  monitor = $monitor
  text = cmd[update:1000] echo "\$(~/.config/hypr/scripts/song-status.sh)"
  color = rgba(242, 243, 244, 0.75)
  font_size = 14
  font_family = SF Pro Text
  position = 20, -10
  halign = left
  valign = top
}

label {
  monitor = $monitor
  text = cmd[update:1000] echo "\$(~/.config/hypr/scripts/network-status.sh)"
  color = rgba(242, 243, 244, 0.75)
  font_size = 16
  font_family = SF Pro Text
  position = -25, -10
  halign = right
  valign = top
}

label {
  monitor = $monitor
  text = cmd[update:1000] echo "\$(~/.config/hypr/scripts/battery-status.sh)"
  color = rgba(242, 243, 244, 0.75)
  font_size = 19
  font_family = SF Pro Text
  position = -50, -8
  halign = right
  valign = top
}

label {
  monitor = $monitor
  text = cmd[update:1000] echo "\$(date +"%A, %B %d")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 20
  font_family = SF Pro Display Bold
  position = 0, 405
  halign = center
  valign = center
}

label {
  monitor = $monitor
  text = cmd[update:1000] echo "\$(date +"%k:%M")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 93
  font_family = SF Pro Display Bold
  position = 0, 310
  halign = center
  valign = center
}

label {
    monitor = $monitor
    text = Ben Neeb
    color = rgba(242, 243, 244, 0.75)
    font_size = 12
    font_family = SF Pro Display Bold
    position = 0, -407
    halign = center
    valign = center
}

label {
    monitor = $monitor
    text = Enter Password
    color = rgba(242, 243, 244, 0.75)
    font_size = 10
    font_family = SF Pro Display
    position = 0, -438
    halign = center
    valign = center
}
eof

