splash = false
preload = /home/ben/wallpaper/cloudscape-3.png
wallpaper {
    monitor = eDP-2
    path = /home/ben/wallpaper/cloudscape-3.png
}

wallpaper {
    monitor = DP-1
    path = /home/ben/wallpaper/cloudscape-3.png
}

wallpaper {
    monitor = DP-2
    path = /home/ben/wallpaper/cloudscape-3.png
}

wallpaper {
    monitor = DP-3
    path = /home/ben/wallpaper/cloudscape-3.png
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/ben/wallpaper/cloudscape-3.png
}
