splash = false
preload = /home/ben/Media/Wallpaper/cloudscape-3.png
wallpaper {
    monitor = eDP-1
    path = /home/ben/Media/Wallpaper/cloudscape-3.png
}

wallpaper {
    monitor = DP-1
    path = /home/ben/Media/Wallpaper/cloudscape-3.png
}

wallpaper {
    monitor = DP-2
    path = /home/ben/Media/Wallpaper/cloudscape-3.png
}

wallpaper {
    monitor = DP-5
    path = /home/ben/Media/Wallpaper/cloudscape-3.png
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/ben/Media/Wallpaper/cloudscape-3.png
}
