#!/bin/bash

## Get data
STATUS="$(playerctl status)"
COVER="/tmp/.music_cover.jpg"
MUSIC_DIR="$HOME/Music"

## Get status
get_status() {
	if [[ $STATUS == *"[Playing]"* ]]; then
		echo ""
	else
		echo "奈"
	fi
}

## Get song
get_song() {
	song=`playerctl metadata --format '{{title}}'`
	if [[ -z "$song" ]]; then
		echo "song"
	else
		echo "$song"
	fi	
}

## Get artist
get_artist() {
	song=`playerctl metadata --format '{{artist}}'`
	artist=`mpc -f %artist% current`
	if [[ -z "$artist" ]]; then
		echo "artist"
	else
		echo "$artist"
	fi	
}

## Get time
get_time() {
	time=`playerctl position`
	if [[ -z "$time" ]]; then
		echo "0"
	else
		echo "$time"
	fi	
}
get_ctime() {
	ctime=`playerctl position`
	if [[ -z "$ctime" ]]; then
		echo "0:00"
	else
		echo "$ctime"
	fi	
}
get_ttime() {
	ttime=`playerctl position`
	if [[ -z "$ttime" ]]; then
		echo "0:00"
	else
		echo "$ttime"
	fi	
}

## Get cover
get_cover() {
	coverArt=$(mktemp)
	curl $(playerctl metadata --format '{{mpris:artUrl}}') --output $(mktemp)
	echo "$coverArt"
}


## Execute accordingly
if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--time" ]]; then
	get_time
elif [[ "$1" == "--ctime" ]]; then
	get_ctime
elif [[ "$1" == "--ttime" ]]; then
	get_ttime
elif [[ "$1" == "--cover" ]]; then
	get_cover
elif [[ "$1" == "--toggle" ]]; then
	playerctl play-pause
elif [[ "$1" == "--next" ]]; then
	{ playerctl next; get_cover; }
elif [[ "$1" == "--prev" ]]; then
	{ playerctl previous; get_cover; }
fi
