hl.on("hyprland.start", function()
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("udiskie &")
	hl.exec_cmd("swaync -c ~/.config/swaync/config.json")
	hl.exec_cmd("~/scripts/wallpaper/loadLast.sh")
	hl.exec_cmd("libinput-gestures-setup start")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("kanata")
	hl.exec_cmd("kbuildsycoca6")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd(
		"cd ~/Documents/programming/ts-js/wallpaper-server/ ; node ~/Documents/programming/ts-js/wallpaper-server/main.js"
	)
	hl.exec_cmd("systemctl --user start xppentablet")
	hl.exec_cmd("syshud -T 10 -p bottom -t 3")
	hl.exec_cmd("walker --gapplication-service")
	hl.exec_cmd("hyprctl setcursor breeze_cursors 24")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("seaf-cli start")
end)
