hl.on("hyprland.start", function()
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("cd ~/Projects/ts-js/wallpaper-server/ ; node ~/Projects/ts-js/wallpaper-server/main.js")
	hl.exec_cmd("hyprctl setcursor breeze_cursors 24")
	hl.exec_cmd("quickshell")
end)
