format = """
[▒▓](#A3A78E)\
[ 󰣇  ](bg:#A3A78E fg:#212121)\
[](bg:#6F9988 fg:#A3A78E)\
$directory\
[](fg:#6F9988 bg:#9B5F45)\
$git_branch\
$git_status\
[](fg:#9B5F45 bg:#212121)\
$nodejs\
$golang\
$php\
$c\
$cmake\
$lua\
$python\
[](fg:#212121 bg:#111111)\
$time\
$memory_usage\
[ ](fg:#111111)\
\n$status $character"""

[character]
success_symbol = "[>](fg:#C59970)"
error_symbol = "[>](fg:#f07178)"

[directory]
style = "fg:#d5ddce bg:#6F9988"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#82aaff"
format = '[[ $symbol $branch ](fg:#d5ddce bg:#9B5F45)]($style)'

[git_status]
style = "bg:#9B5F45"
format = '[[($all_status$ahead_behind )](fg:#d5ddce bg:#9B5F45)]($style)'

[nodejs]
symbol = ""
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212121)]($style)'

[rust]
symbol = ""
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212121)]($style)'

[golang]
symbol = ""
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212121)]($style)'

[php]
symbol = ""
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212121)]($style)'

[c]
symbol = "c"
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212121)]($style)'

[lua]
symbol = ""
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212121)]($style)'

[python]
symbol = ""
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212121)]($style)'

[cmake]
symbol = "△"
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212121)]($style)'

[time]
disabled = false
time_format = "%I:%M%p" # hour:minute format
use_12hr = true
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#111111)]($style)'
