format = """
[▒▓](#484A53)\
[ 󰣇  ](bg:#484A53 fg:#212121)\
[](bg:#364666 fg:#484A53)\
$directory\
[](fg:#364666 bg:#2B3547)\
$git_branch\
$git_status\
[](fg:#2B3547 bg:#212121)\
$nodejs\
$golang\
$php\
$c\
$cmake\
$lua\
$python\
[](fg:#212121 bg:#111111)\
$time\
$memory_usage\
[ ](fg:#111111)\
\n$status $character"""

[character]
success_symbol = "[>](fg:#3A4351)"
error_symbol = "[>](fg:#f07178)"

[directory]
style = "fg:#c2c2c3 bg:#364666"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#82aaff"
format = '[[ $symbol $branch ](fg:#c2c2c3 bg:#2B3547)]($style)'

[git_status]
style = "bg:#2B3547"
format = '[[($all_status$ahead_behind )](fg:#c2c2c3 bg:#2B3547)]($style)'

[nodejs]
symbol = ""
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212121)]($style)'

[rust]
symbol = ""
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212121)]($style)'

[golang]
symbol = ""
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212121)]($style)'

[php]
symbol = ""
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212121)]($style)'

[c]
symbol = "c"
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212121)]($style)'

[lua]
symbol = ""
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212121)]($style)'

[python]
symbol = ""
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212121)]($style)'

[cmake]
symbol = "△"
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212121)]($style)'

[time]
disabled = false
time_format = "%I:%M%p" # hour:minute format
use_12hr = true
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#111111)]($style)'
