cursor                #c5c6c5
foreground            #c5c6c5
selection_foreground  #1a1c18
selection_background  #c5c6c5
color0                #1a1c18
color8                #6d745e
color1                #727c8a
color9                #98A6B9
color2                #758191
color10               #9DADC2
color3                #7f8996
color11               #AAB7C9
color4                #8a93a0
color12               #B9C5D6
color5                #8e99a8
color13               #BECDE0
color6                #9299a5
color14               #C3CDDD
color7                #929c92
color15               #c5c6c5
active_border_color   #9299a5
inactive_border_color #9DADC2
