# Disable audio bell
enable_audio_bell no

# Fonts
font_family           family="JetBrainsMono Nerd Font"
bold_font             auto
italic_font           auto
bold_italic_font      auto
font_size             11.0

disable_ligatures cursor

symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000,U+E0A0-U+E0A3,U+E0B0-U+E0C8,U+E0CA,U+E0CC-U+E0D2,U+E0D4,U+E200-U+E2A9,U+E5FA-U+E634,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF Symbols Nerd Font Mono

# Transparency
background_opacity 0.9

# Set neovim as editor
editor nvim

# Do not confirm on close
confirm_os_window_close 0

# Scrollback
scrollback_lines 10000
scrollback_indicator_opacity 0.2

allow_remote_control socket-only
listen_on unix:/tmp/kitty

# Some mappings for new tabs and windows
map f5 launch --cwd=current
map f6 launch --cwd=current --type=tab

# Layout
enabled_layouts tall

# Allow use of ctrl+(shift)+tab
map  ctrl+tab        send_text normal,application \x1b[9;5u
map  ctrl+shift+tab  send_text normal,application \x1b[9;6u

# Unicode menu
map ctrl+shift+u kitten unicode_input --tab name

shell /usr/bin/env zsh

# BEGIN_KITTY_THEME
# Pywal
include current-theme.conf
# END_KITTY_THEME
