#!/usr/bin/env bash

brightness=$(brightnessctl -d intel_backlight get)

amount=25
if [ $brightness -lt 50 ]; then
    amount=5
fi

if [[ "$2" == "max" ]]; then
    amount=100%
fi

echo
if [[ "$1" == "sub" ]]; then
    brightnessctl -d intel_backlight set "$amount"-
elif [[ "$1" == "add" ]]; then
    brightnessctl -d intel_backlight set +"$amount"
fi
